name: Intégration Continue (CI)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du dépôt
      uses: actions/checkout@v2

    - name: Configurer Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Construire l'image Docker
      run: docker build -t gabarit-python .

    - name: Exécuter les tests
      run: docker run gabarit-python python -m unittest discover
