name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Parfois, flake8 peut être très strict avec les normes de lint. 
    # Si nécessaire, vous pouvez commenter le bloc de code ci-dessous.
    - name: Run flake8
      run: |
        flake8 src tests

    - name: Run pylint
      run: |
        pylint src tests

    - name: Run unittest
      run: |
        python -m unittest discover -s tests
